/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gitcompany.detektor_altek;
import java.awt.Font;

/**
 *
 * @author kkile
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Detector dt = new Detector();
        Font font = new Font("Stencil", Font.PLAIN, 48);
        Font font2 = new Font("Tw Cen MT", Font.PLAIN, 48);
        jLTitle.setFont(new Font("Stencil", Font.BOLD, 60));
        jLNick.setFont(font);
        jLIP.setFont(font);
        jLAddress.setFont(font);
        jLStatus.setFont(font);
        jLNick_A.setFont(font2);
        jLIP_A.setFont(font2);
        jLAddress_A.setFont(font2);
        jLStatus_A.setFont(font2);
        jLResultTitle.setFont(new Font("Stencil", Font.PLAIN, 54));
        jLResult.setFont(new Font("Stencil", Font.PLAIN, 60));
    }
    //bruh
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitle = new javax.swing.JLabel();
        jLNick = new javax.swing.JLabel();
        jLResultTitle = new javax.swing.JLabel();
        jLResult = new javax.swing.JLabel();
        jLNick_A = new javax.swing.JLabel();
        jLIP = new javax.swing.JLabel();
        jLIP_A = new javax.swing.JLabel();
        jLAddress = new javax.swing.JLabel();
        jLAddress_A = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jLStatus_A = new javax.swing.JLabel();
        jLIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLTitle.setBackground(new java.awt.Color(123, 44, 191));
        jLTitle.setFont(new java.awt.Font("Stencil", 1, 60)); // NOI18N
        jLTitle.setForeground(new java.awt.Color(255, 0, 51));
        jLTitle.setText("Altko-Detektor");

        jLNick.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLNick.setForeground(new java.awt.Color(255, 0, 51));
        jLNick.setText("Nick:");

        jLResultTitle.setFont(new java.awt.Font("Stencil", 2, 54)); // NOI18N
        jLResultTitle.setForeground(new java.awt.Color(255, 0, 51));
        jLResultTitle.setText("Wynik testu:");

        jLResult.setFont(new java.awt.Font("Stencil", 1, 60)); // NOI18N
        jLResult.setForeground(new java.awt.Color(204, 0, 0));
        jLResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLResult.setText(":)))");

        jLNick_A.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLNick_A.setForeground(new java.awt.Color(204, 0, 0));
        jLNick_A.setText("jwidscj");

        jLIP.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLIP.setForeground(new java.awt.Color(255, 0, 51));
        jLIP.setText("Adres IP:");

        jLIP_A.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLIP_A.setForeground(new java.awt.Color(204, 0, 0));
        jLIP_A.setText("10.823.612");

        jLAddress.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLAddress.setForeground(new java.awt.Color(255, 0, 51));
        jLAddress.setText("Adres:");

        jLAddress_A.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLAddress_A.setForeground(new java.awt.Color(204, 0, 0));
        jLAddress_A.setText("ihjkjhgfdhj");

        jLStatus.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLStatus.setForeground(new java.awt.Color(255, 0, 51));
        jLStatus.setText("Status:");

        jLStatus_A.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLStatus_A.setForeground(new java.awt.Color(204, 0, 0));
        jLStatus_A.setText("ONLINE");

        jLIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kacpe\\OneDrive\\Dokumenty\\GitHub\\Desktopowe\\Detektor_Altek\\src\\main\\img\\ziut.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLAddress_A, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLNick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLNick_A, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLStatus_A, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLIP, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLIP_A, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLResult, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLResultTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLIcon)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTitle)
                    .addComponent(jLIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNick)
                    .addComponent(jLNick_A))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIP)
                    .addComponent(jLIP_A))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAddress)
                    .addComponent(jLAddress_A))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStatus)
                    .addComponent(jLStatus_A))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLResultTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLResult)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAddress;
    private javax.swing.JLabel jLAddress_A;
    private javax.swing.JLabel jLIP;
    private javax.swing.JLabel jLIP_A;
    private javax.swing.JLabel jLIcon;
    private javax.swing.JLabel jLNick;
    private javax.swing.JLabel jLNick_A;
    private javax.swing.JLabel jLResult;
    private javax.swing.JLabel jLResultTitle;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLStatus_A;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
